services:
  mysql:
    image: mysql:8.0
    container_name: impact-island-db
    env_file:
      - ../.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
    volumes:
      - impact-island-data:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  impact-island-data:
